In [1]:
import numpy as np

In [2]:

my_list1 = [1, 2, 3, 4]
print(my_list1)


[1, 2, 3, 4]


In [3]:
my_array1 = np.array(my_list1)

print(my_array1)


[1 2 3 4]


In [4]:
my_list2 = [11,22,33,44]

my_lists = [my_list1, my_list2]

my_array2 = np.array(my_lists)

print(my_array2)

print(my_array2.shape)

print(np.zeros(5))

print(np.ones([5,5]))



[[ 1  2  3  4]
 [11 22 33 44]]
(2, 4)
[0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [5]:
indentity_matrix = np.eye(5)
print(indentity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
arr1 = np.arange(1,21).reshape(4,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
arr2 = np.arange(21,46).reshape(5,5)
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [9]:
np.dot(arr1,arr2)

array([[ 515,  530,  545,  560,  575],
       [1290, 1330, 1370, 1410, 1450],
       [2065, 2130, 2195, 2260, 2325],
       [2840, 2930, 3020, 3110, 3200]])

In [ ]:
arr3d = np.arange(1,51).reshape((5,5,2))
arr3d